kind: Service
apiVersion: v1
metadata:
  name: rabbitmq
spec:
  selector:
    app.kubernetes.io/instance: rabbitmq
  type: NodePort
  ports:
    - port: 15672
      targetPort: 15672
      nodePort: 31567
