kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-service
spec:
  selector:
    app.kubernetes.io/instance: rabbitmq
  type: NodePort
  ports:
    - name: httpk get
      port: 15672
      targetPort: 15672
      nodePort: 31567
    - name: amqp
      port: 5672
      targetPort: 5672
      nodePort: 31568
