apiVersion: batch/v1
kind: Job
metadata:
  name: job-nodejs
spec:
  completions: 4
  parallelism: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: nodejs-job
          image: khannedy/nodejs-job
